# Generated by Django 5.1.8 on 2026-05-09 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_concepto", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "concepto",
                "verbose_name_plural": "conceptos",
            },
        ),
        migrations.CreateModel(
            name="TipoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "tipo de movimiento",
                "verbose_name_plural": "tipos de movimiento",
            },
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ultimos_4_digitos",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "tipo_tarjeta",
                    models.CharField(
                        choices=[
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("efectivo", "Efectivo"),
                        ],
                        default="debito",
                        max_length=20,
                    ),
                ),
                ("banco", models.CharField(max_length=100)),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarjetas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tarjeta",
                "verbose_name_plural": "tarjetas",
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                (
                    "medio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tarjeta", "Tarjeta"),
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="finances.concepto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarjeta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos",
                        to="finances.tarjeta",
                    ),
                ),
                (
                    "tarjeta_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_recibidas",
                        to="finances.tarjeta",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="finances.tipomovimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento",
                "verbose_name_plural": "movimientos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="concepto",
            name="tipo_default",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conceptos",
                to="finances.tipomovimiento",
                verbose_name="tipo por defecto",
            ),
        ),
        migrations.CreateModel(
            name="PresupuestoMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_asignado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("mes", models.DateField()),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="finances.concepto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "presupuesto mensual",
                "verbose_name_plural": "presupuestos mensuales",
                "unique_together": {("usuario", "concepto", "mes")},
            },
        ),
    ]
